modelsim:
	vsim -c -do run_modelsim.do

gui:
	vsim -do run_modelsim.do

vcs:
	./run_vcs.do
clean:
	rm -rf work/
	rm -f transcript
	rm -rf csrc
	rm -rf simv.daidir
	rm -f simv
	rm -f vcdplus.vpd
	rm -f vcs.log
	rm -f ucli.key
	rm -f vc_hdrs.h
